### ISSUE TITLE
Event listener

### ISSUE THREAD

**Issue by Mluna97** [FranciscoJavierPRamos/Android-FilterView#4]
Hi! Nice work with this lib.
I was trying to handle the events but I don't know how could I close this view. I only found the show but not the reverse action.

Thanks!

**Comment by Mluna97** [comment]
Already got It. If the "OnFilterCanceled" isn't set, the cancel button doesn't actually work.
Kinda wierd but It works now.

Nice lib, did you kept working on it?

**Comment by javierpe** [comment]
I do not have time to continue with the project, but if I have many ideas!
